---
- name: copy kubernetes.repo
  template:
    src: "kubernetes.repo.j2"
    dest: "/etc/yum.repos.d/kubernetes.repo"
    mode: 0644

- name: install kubernetes packages
  dnf:
    name: ['kubelet{{ kube_rpm_version | default("") }}', 'kubeadm{{ kube_rpm_version | default("") }}', 'kubectl{{ kube_rpm_version | default("") }}']
    disable_excludes: kubernetes
    state: present
